# To install, run:
# $ ansible-playbook -i localhost, site.yml [-e "@defaults/main.yml"]
#
# To list your gpg keys, run: 
# $ gpg --list-keys
#

- hosts: localhost
  connection: local
  vars_files:
    - defaults/main.yml
  tasks:
    - include_tasks: tasks/main.yml
